general.import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
  '~\AppData\Roaming\alacritty\themes\themes\catppuccin_mocha.toml',
]

[env]
TERM = "alacritty"

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
